# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(808, 617)
        MainWindow.setMouseTracking(True)
        MainWindow.setTabletTracking(True)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ClearButton = QtWidgets.QPushButton(self.centralwidget)
        self.ClearButton.setGeometry(QtCore.QRect(730, 0, 61, 51))
        self.ClearButton.setObjectName("ClearButton")
        self.brushSizeSlider = QtWidgets.QSlider(self.centralwidget)
        self.brushSizeSlider.setGeometry(QtCore.QRect(530, 20, 160, 16))
        self.brushSizeSlider.setMinimum(2)
        self.brushSizeSlider.setMaximum(15)
        self.brushSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brushSizeSlider.setObjectName("brushSizeSlider")
        self.brushSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.brushSizeLabel.setGeometry(QtCore.QRect(540, 0, 131, 20))
        self.brushSizeLabel.setObjectName("brushSizeLabel")
        self.writeToBaseButton = QtWidgets.QPushButton(self.centralwidget)
        self.writeToBaseButton.setGeometry(QtCore.QRect(430, 10, 81, 31))
        self.writeToBaseButton.setObjectName("writeToBaseButton")
        self.metricTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.metricTextEdit.setGeometry(QtCore.QRect(270, 10, 31, 31))
        self.metricTextEdit.setObjectName("metricTextEdit")
        self.bordersButton = QtWidgets.QPushButton(self.centralwidget)
        self.bordersButton.setGeometry(QtCore.QRect(180, 12, 75, 31))
        self.bordersButton.setObjectName("bordersButton")
        self.borderTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.borderTextEdit.setGeometry(QtCore.QRect(310, 10, 31, 31))
        self.borderTextEdit.setObjectName("borderTextEdit")
        self.charTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.charTextEdit.setGeometry(QtCore.QRect(350, 10, 81, 31))
        self.charTextEdit.setObjectName("charTextEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 808, 22))
        self.menubar.setObjectName("menubar")
        self.menuClear = QtWidgets.QMenu(self.menubar)
        self.menuClear.setObjectName("menuClear")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.ClearAction = QtWidgets.QAction(MainWindow)
        self.ClearAction.setObjectName("ClearAction")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.menuClear.addAction(self.ClearAction)
        self.menubar.addAction(self.menuClear.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.brushSizeLabel.setText(_translate("MainWindow", "Размер кисти 10"))
        self.writeToBaseButton.setText(_translate("MainWindow", "Write"))
        self.bordersButton.setText(_translate("MainWindow", "Borders"))
        self.menuClear.setTitle(_translate("MainWindow", "File"))
        self.ClearAction.setText(_translate("MainWindow", "Clear"))
        self.action_2.setText(_translate("MainWindow", "Цвет"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
        self.action7.setText(_translate("MainWindow", "7"))
